### ISSUE TITLE
segfault on big documents

### ISSUE THREAD

**Issue by ezegolub** [elasticsearch/elasticsearch-py#168]
When trying to get() a 2.8mb document, i get a segfault. When i get other normally sized docs, it all works well. Anyone else had this problem? 

Here's the relevant part of the logs:
```
Fatal Python error: Segmentation fault

Current thread 0x00007f518b773740 (most recent call first):
  File "/usr/lib/python2.7/json/decoder.py", line 382 in raw_decode
  File "/usr/lib/python2.7/json/decoder.py", line 366 in decode
  File "/usr/lib/python2.7/json/__init__.py", line 338 in loads
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/serializer.py", line 35 in loads
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/serializer.py", line 73 in loads
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 295 in perform_request
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 272 in get
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68 in _wrapped


Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/billiard/pool.py", line 1169, in mark_as_worker_lost
    human_status(exitcode)),
WorkerLostError: Worker exited prematurely: signal 11 (SIGSEGV).
```

**Comment by HonzaKral** [comment]
Closing this due to lack of information. Either way this error was not generated by `elasticsearch-py` but by the `json` builtin module.
