### ISSUE TITLE
thrift in Python 3 (No module named 'ttypes'

### ISSUE THREAD

**Issue by kelp404** [elasticsearch/elasticsearch-py#184]
Hello,

I can't create a thrift connection in Python 3, but it is work in Python 2.7.
```
elasticsearch.ThriftConnection()
```

```
Python 3.4.0 (default, Apr 11 2014, 13:05:11)
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from elasticsearch.connection.esthrift import Rest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/elasticsearch/connection/esthrift/Rest.py", line 10, in <module>
    from ttypes import *
ImportError: No module named 'ttypes'
```

**Comment by HonzaKral** [comment]
Yes, it is die to the `thrift` python library not being python 3 compatible. Unfortunately there isn't anything we can do.

**Comment by kelp404** [comment]
Hello @HonzaKral 
Thank you very mush.
